/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * GENERATED from the agent24-protocol Rust crate (task B4) — do not edit by hand; regenerate with `cargo run -p agent24-protocol --bin export-schema`. Wire contract details: docs/specs/SPEC-002-protocol.md §3 (message classes: approval.required is the only REQUEST-class event, answered via POST /api/v1/approvals/{id}; everything else is NOTIFICATION). Conventions: snake_case; ULID ids; ISO 8601 UTC ts; nullable fields always present as null; per-connection monotonic seq; clients ignore unknown types/fields.
 */
export type Agent24V1WebSocketEventProtocol = {
  seq: number;
  ts: string;
  /**
   * Protocol major version — always 1
   */
  v: 1;
  [k: string]: unknown;
} & (
  | {
      payload: RunStartedPayload;
      type: "run.started";
      [k: string]: unknown;
    }
  | {
      payload: ModelDeltaPayload;
      type: "model.delta";
      [k: string]: unknown;
    }
  | {
      payload: RunCompletedPayload;
      type: "run.completed";
      [k: string]: unknown;
    }
  | {
      payload: RunFailedPayload;
      type: "run.failed";
      [k: string]: unknown;
    }
  | {
      payload: RunCancelledPayload;
      type: "run.cancelled";
      [k: string]: unknown;
    }
  | {
      payload: ToolStartedPayload;
      type: "tool.started";
      [k: string]: unknown;
    }
  | {
      payload: ToolCompletedPayload;
      type: "tool.completed";
      [k: string]: unknown;
    }
  | {
      payload: Approval;
      type: "approval.required";
      [k: string]: unknown;
    }
  | {
      payload: ApprovalResolvedPayload;
      type: "approval.resolved";
      [k: string]: unknown;
    }
  | {
      payload: ScheduleFiredPayload;
      type: "schedule.fired";
      [k: string]: unknown;
    }
  | {
      payload: ScheduleDisabledPayload;
      type: "schedule.disabled";
      [k: string]: unknown;
    }
);
/**
 * Closed set per protocol/events.schema.json (a running tool never emits
 * tool.completed)
 */
export type ToolCompletedStatus = "completed" | "failed" | "denied";
/**
 * timed_out is equivalent to a denial (fail-closed)
 */
export type ApprovalStatus = "pending" | "approved" | "denied" | "aborted" | "timed_out";

export interface RunStartedPayload {
  run_id: string;
  /**
   * Set when fired by a schedule
   */
  schedule_id: string | null;
  /**
   * Null for transient runs (e.g. /chat)
   */
  session_id: string | null;
  [k: string]: unknown;
}
export interface ModelDeltaPayload {
  run_id: string;
  /**
   * Streaming text increment
   */
  text: string;
  [k: string]: unknown;
}
export interface RunCompletedPayload {
  output: RunOutputPayload;
  run_id: string;
  usage: Usage;
  [k: string]: unknown;
}
export interface RunOutputPayload {
  text: string;
  [k: string]: unknown;
}
export interface Usage {
  completion_tokens: number;
  cost_usd?: number;
  prompt_tokens: number;
  total_tokens: number;
  [k: string]: unknown;
}
export interface RunFailedPayload {
  error: ErrorBody;
  run_id: string;
  [k: string]: unknown;
}
export interface ErrorBody {
  /**
   * Open enum: invalid_request, unauthorized, not_found, conflict,
   * approval_already_resolved, provider_unavailable,
   * run_not_cancellable (reserved), payload_too_large, internal
   */
  code: string;
  details?: {
    [k: string]: unknown;
  } | null;
  message: string;
  [k: string]: unknown;
}
export interface RunCancelledPayload {
  run_id: string;
  [k: string]: unknown;
}
export interface ToolStartedPayload {
  /**
   * Summarized — full input is audit-only
   */
  input_summary: string;
  run_id: string;
  tool: string;
  tool_call_id: string;
  [k: string]: unknown;
}
export interface ToolCompletedPayload {
  output_summary: string | null;
  run_id: string;
  status: ToolCompletedStatus;
  tool_call_id: string;
  [k: string]: unknown;
}
export interface Approval {
  /**
   * Server-driven open set — UIs render exactly this list
   */
  available_decisions: string[];
  created_at: string;
  decided_at: string | null;
  /**
   * Set once resolved
   */
  decision: Decision | null;
  /**
   * After this instant the approval resolves to timed_out
   */
  expires_at: string;
  id: string;
  /**
   * Open enum: exec | fs_write | network | module
   */
  kind: string;
  /**
   * Kind-specific detail (e.g. command argv, cwd, reason)
   */
  payload: {
    [k: string]: unknown;
  };
  run_id: string;
  status: ApprovalStatus;
  summary: string;
  tool_call_id: string;
  [k: string]: unknown;
}
/**
 * OPEN SET, server-driven: valid `type` values for a given approval are
 * exactly its `available_decisions`. Known: approve, approve_for_session,
 * deny (reason required), abort. Future types may carry extra fields (kept
 * in `extra` via flatten). Fail-closed: the implementation default (broken
 * channel, cancelled run, daemon restart) is equivalent to abort/deny.
 */
export interface Decision {
  /**
   * Required when kind == "deny"
   */
  reason?: string | null;
  type: string;
  [k: string]: unknown;
}
/**
 * Broadcast so every connected client converges
 */
export interface ApprovalResolvedPayload {
  approval_id: string;
  /**
   * Open enum — the Decision.type that resolved it, or timed_out/aborted
   */
  decision_type: string;
  run_id: string;
  [k: string]: unknown;
}
export interface ScheduleFiredPayload {
  run_id: string;
  schedule_id: string;
  [k: string]: unknown;
}
export interface ScheduleDisabledPayload {
  /**
   * Open enum; currently only consecutive_failures
   */
  reason: string;
  schedule_id: string;
  [k: string]: unknown;
}
