/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Single source of truth for messages on GET /api/v1/events (hand-written until task B4 switches generation to the agent24-protocol Rust crate with a CI zero-drift check; since B1 the Rust types are locked to this file via fixture round-trip tests). Human-readable spec: docs/specs/SPEC-002-protocol.md §3. Two message classes: NOTIFICATION (one-way, no reply — x-kind: notification) and REQUEST (client MUST answer via REST — x-kind: request; currently only approval.required, answered via POST /api/v1/approvals/{id}). Conventions: snake_case fields; ULID string ids; ISO 8601 UTC timestamps; nullable fields are ALWAYS present on the wire with value null; `seq` is monotonically increasing per connection (a gap means the client must reconcile via REST — v1 has no replay); clients MUST ignore unknown event types and unknown fields (forward compatibility). Rust: #[serde(tag = "type")] enum with explicit per-variant #[serde(rename = "run.started")] dotted names — never rename_all.
 */
export type Agent24V1WebSocketEventProtocol =
  | RunStarted
  | RunCompleted
  | RunFailed
  | RunCancelled
  | ModelDelta
  | ToolStarted
  | ToolCompleted
  | ApprovalRequired
  | ApprovalResolved
  | ScheduleFired
  | ScheduleDisabled;
export type RunStarted = Envelope & {
  type?: "run.started";
  payload?: {
    run_id: string;
    /**
     * Null for transient runs (e.g. /chat)
     */
    session_id: string | null;
    /**
     * Set when fired by a schedule
     */
    schedule_id: string | null;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
export type RunCompleted = Envelope & {
  type?: "run.completed";
  payload?: {
    run_id: string;
    output: {
      text: string;
      [k: string]: unknown;
    };
    usage: Usage;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
export type RunFailed = Envelope & {
  type?: "run.failed";
  payload?: {
    run_id: string;
    error: ErrorBody;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
export type RunCancelled = Envelope & {
  type?: "run.cancelled";
  payload?: {
    run_id: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
export type ModelDelta = Envelope & {
  type?: "model.delta";
  payload?: {
    run_id: string;
    /**
     * Streaming text increment
     */
    text: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
export type ToolStarted = Envelope & {
  type?: "tool.started";
  payload?: {
    run_id: string;
    tool_call_id: string;
    tool: string;
    /**
     * Summarized — full input is audit-only
     */
    input_summary: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
export type ToolCompleted = Envelope & {
  type?: "tool.completed";
  payload?: {
    run_id: string;
    tool_call_id: string;
    status: "completed" | "failed" | "denied";
    output_summary: string | null;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
/**
 * REQUEST class: the client MUST answer via POST /api/v1/approvals/{payload.id}. Fail-closed: no answer before payload.expires_at resolves to timed_out (equivalent to denial).
 */
export type ApprovalRequired = Envelope & {
  type?: "approval.required";
  payload?: Approval;
  [k: string]: unknown;
};
/**
 * Broadcast so every connected client converges (e.g. TUI approves, desktop dismisses its dialog)
 */
export type ApprovalResolved = Envelope & {
  type?: "approval.resolved";
  payload?: {
    approval_id: string;
    run_id: string;
    /**
     * Open enum — the Decision.type that resolved it, or timed_out/aborted
     */
    decision_type: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
export type ScheduleFired = Envelope & {
  type?: "schedule.fired";
  payload?: {
    schedule_id: string;
    run_id: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
export type ScheduleDisabled = Envelope & {
  type?: "schedule.disabled";
  payload?: {
    schedule_id: string;
    /**
     * Open enum
     */
    reason: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};

/**
 * Common envelope for every WS message
 */
export interface Envelope {
  /**
   * Protocol major version
   */
  v: 1;
  /**
   * Monotonic per-connection sequence number
   */
  seq: number;
  ts: string;
  type: string;
  payload: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Usage {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
  cost_usd?: number;
  [k: string]: unknown;
}
export interface ErrorBody {
  /**
   * Open enum — see openapi.yaml ErrorBody
   */
  code: string;
  message: string;
  details?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Mirror of openapi.yaml Approval (kept in lockstep until B4 generation unifies both files from Rust types)
 */
export interface Approval {
  id: string;
  run_id: string;
  tool_call_id: string;
  /**
   * Open enum
   */
  kind: string;
  summary: string;
  payload: {
    [k: string]: unknown;
  };
  /**
   * Server-driven open set — UIs render exactly this list, never a hardcoded one
   */
  available_decisions: string[];
  status: "pending" | "approved" | "denied" | "aborted" | "timed_out";
  decision: Decision | null;
  expires_at: string;
  created_at: string;
  decided_at: string | null;
  [k: string]: unknown;
}
/**
 * Open set, server-driven — see openapi.yaml Decision. Known types: approve, approve_for_session, deny (reason required), abort. Fail-closed: implementation default equals abort/deny, never approve.
 */
export interface Decision {
  type: string;
  /**
   * Required when type=deny
   */
  reason?: string;
  [k: string]: unknown;
}
