/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and backend identity */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pass-through chat (compat path; superseded by runs long-term)
         * @description Stateless from the client's perspective, but the server creates a
         *     **transient Run** (session_id = null) per call and emits the normal
         *     `run.started` / `model.delta` / `run.completed` events for it.
         */
        post: operations["postChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List known models with tier and load status */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate token/cost usage since daemon start */
        get: operations["getUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sessions */
        get: operations["listSessions"];
        put?: never;
        /** Create a session */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List runs, optionally filtered by status */
        get: operations["listRuns"];
        put?: never;
        /** Start an agent run (async; progress via WS events) */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request cancellation (idempotent; valid in any state)
         * @description Idempotent: cancelling an already-terminal run returns 202 with the
         *     current (unchanged) run. Cancellation of a streaming run must take
         *     effect within 1s (see TASKS C2 acceptance).
         */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List approvals (polling fallback for TUI/UI) */
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit the decision for a pending approval
         * @description Body is a Decision object. The decision type MUST be one of the
         *     `available_decisions` advertised on the approval. Fail-closed semantics:
         *     an expired or otherwise resolved approval returns 409
         *     `approval_already_resolved` and the submitted decision is discarded.
         */
        post: operations["decideApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List schedules */
        get: operations["listSchedules"];
        put?: never;
        /** Create a schedule */
        post: operations["createSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one schedule */
        get: operations["getSchedule"];
        put?: never;
        post?: never;
        /** Delete a schedule */
        delete: operations["deleteSchedule"];
        options?: never;
        head?: never;
        /**
         * Partially update a schedule
         * @description Any subset of name/enabled/spec/action/delivery. Changing `spec`
         *     recomputes `next_run_at` immediately.
         */
        patch: operations["updateSchedule"];
        trace?: never;
    };
    "/schedules/{id}/run_now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger one run immediately (does not change next_run_at) */
        post: operations["runScheduleNow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request graceful daemon shutdown (authenticated)
         * @description The bearer token proves the caller owns this daemon instance — the CLI
         *     uses this instead of signalling a pid from a possibly-stale state file.
         *     agent24d only until the node mock gains parity.
         */
        post: operations["shutdownDaemon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered tools (builtin / mcp / module) */
        get: operations["listTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tool-overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the user's local risk overrides
         * @description User-local rules adjusting a tool's risk_class. NEVER written by a module, persona, or MCP server: a package may declare which tools it wants, but only the user decides how far to trust them.
         */
        get: operations["listToolOverrides"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tool-overrides/{pattern}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Glob over tool names (`*` any run, `?` one char). It is the rule's identity, so writing the same pattern twice replaces it. */
                pattern: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Create or replace one risk override
         * @description The rule is stored as written. Whether it takes EFFECT is decided at dispatch: a builtin's class may be tightened but never relaxed, since `external` on third-party code is a guess the user may correct while a builtin's class is not. A stored-but-inert rule stays listed and revocable rather than being silently dropped.
         */
        put: operations["setToolOverride"];
        post?: never;
        /** Remove one risk override */
        delete: operations["deleteToolOverride"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            status: "ok";
            version: string;
            /**
             * @description Open enum — clients must tolerate unknown values
             * @example node
             * @example rust
             */
            backend: string;
        };
        ChatMessage: {
            /**
             * @description Open enum
             * @example system
             * @example user
             * @example assistant
             */
            role: string;
            content: string;
        };
        ChatRequest: {
            messages: components["schemas"]["ChatMessage"][];
            /** @description Model id override; null/omitted = daemon default */
            model?: string | null;
        };
        ChatResponse: {
            message: components["schemas"]["ChatMessage"];
            usage: components["schemas"]["Usage"];
        };
        Session: {
            id: string;
            title: string;
            /**
             * @description Open enum
             * @example desktop
             * @example cli
             * @example tui
             * @example schedule
             * @example wechat
             * @example nostr
             */
            channel: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SessionCreate: {
            /** @default  */
            title: string;
            /** @default desktop */
            channel: string;
        };
        /**
         * @description State machine (only legal transitions):
         *     queued → running → completed | failed | cancelled;
         *     running ⇄ awaiting_approval;
         *     queued|running|awaiting_approval → cancelled.
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "awaiting_approval" | "completed" | "failed" | "cancelled";
        RunInput: {
            prompt: string;
            model_override?: string | null;
        };
        RunOutput: {
            text: string;
        };
        Run: {
            id: string;
            /** @description Null for transient runs (e.g. created by /chat) */
            session_id: string | null;
            status: components["schemas"]["RunStatus"];
            input: components["schemas"]["RunInput"];
            /** @description Present when status=completed */
            output: components["schemas"]["RunOutput"] | null;
            /** @description Present when status=failed */
            error: components["schemas"]["ErrorBody"] | null;
            usage: components["schemas"]["Usage"];
            /** @description Set when the run was fired by a schedule */
            schedule_id: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            ended_at: string | null;
        };
        RunCreate: {
            /** @description Omit/null to create a transient run */
            session_id?: string | null;
            prompt: string;
            model_override?: string | null;
        };
        /** @enum {string} */
        ToolCallStatus: "running" | "completed" | "failed" | "denied";
        ToolCall: {
            id: string;
            run_id: string;
            tool: string;
            /** @description Tool input (full detail persisted for audit; summarized externally) */
            input: {
                [key: string]: unknown;
            };
            status: components["schemas"]["ToolCallStatus"];
            /** @description Null while running */
            output_summary: string | null;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at: string | null;
        };
        /**
         * @description timed_out is equivalent to a denial (fail-closed)
         * @enum {string}
         */
        ApprovalStatus: "pending" | "approved" | "denied" | "aborted" | "timed_out";
        Approval: {
            id: string;
            run_id: string;
            tool_call_id: string;
            /**
             * @description Open enum
             * @example exec
             * @example fs_write
             * @example network
             * @example module
             */
            kind: string;
            /** @description Human-readable one-liner of what is being requested */
            summary: string;
            /** @description Kind-specific detail (e.g. command argv, cwd, reason) */
            payload: {
                [key: string]: unknown;
            };
            /**
             * @description Server-driven decision set. UIs MUST render exactly this list and
             *     MUST NOT hardcode decision options (open set — tolerate unknown values).
             * @example [
             *       "approve",
             *       "approve_for_session",
             *       "deny",
             *       "abort"
             *     ]
             */
            available_decisions: string[];
            status: components["schemas"]["ApprovalStatus"];
            /** @description Set once resolved */
            decision: components["schemas"]["Decision"] | null;
            /**
             * Format: date-time
             * @description After this instant the approval resolves to timed_out
             */
            expires_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            decided_at: string | null;
        };
        /**
         * @description OPEN SET, server-driven: valid `type` values for a given approval are
         *     exactly its `available_decisions` — clients submit one of those and
         *     MUST NOT assume a fixed list; servers reject types not advertised
         *     (400 invalid_request). Known types and their semantics:
         *     - `approve` — approve this request only
         *     - `approve_for_session` — approve and skip future approvals of the
         *       same kind in this session
         *     - `deny` — deny but let the run continue (`reason` REQUIRED and fed
         *       back to the model)
         *     - `abort` — deny and cancel the whole run
         *     Future types (e.g. `approve_and_remember`) may carry extra fields —
         *     hence additionalProperties: true.
         *     Fail-closed: the implementation default (broken channel, cancelled
         *     run, daemon restart) is equivalent to abort/deny — never approve.
         */
        Decision: {
            /**
             * @description Open enum
             * @example approve
             * @example approve_for_session
             * @example deny
             * @example abort
             */
            type: string;
            /** @description Required when type=deny */
            reason?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description When to fire */
        ScheduleSpec: {
            /** @constant */
            type: "cron";
            /** @description 5/6-field cron expression */
            expr: string;
            /** @description IANA timezone (e.g. Asia/Shanghai); default UTC */
            tz?: string;
        } | {
            /** @constant */
            type: "every";
            secs: number;
        } | {
            /** @constant */
            type: "at";
            /** Format: date-time */
            ts: string;
        };
        ScheduleAction: {
            /** @constant */
            type: "agent_run";
            prompt: string;
            /** @description Null = each firing creates a transient run */
            session_id?: string | null;
            model_override?: string | null;
        };
        /** @description Open set — M-F adds channel/webhook/email targets */
        DeliveryTarget: {
            /** @example desktop_notification */
            type: string;
        } & {
            [key: string]: unknown;
        };
        Schedule: {
            id: string;
            name: string;
            enabled: boolean;
            spec: components["schemas"]["ScheduleSpec"];
            action: components["schemas"]["ScheduleAction"];
            delivery: components["schemas"]["DeliveryTarget"][];
            /** Format: date-time */
            last_run_at: string | null;
            /**
             * Format: date-time
             * @description Null when disabled or one-shot already fired
             */
            next_run_at: string | null;
            /** @description Auto-disables the schedule at 5 (emits schedule.disabled) */
            consecutive_failures: number;
        };
        ScheduleCreate: {
            name: string;
            /** @default true */
            enabled: boolean;
            spec: components["schemas"]["ScheduleSpec"];
            action: components["schemas"]["ScheduleAction"];
            /** @default [] */
            delivery: components["schemas"]["DeliveryTarget"][];
        };
        /** @description Any subset; changing spec recomputes next_run_at */
        ScheduleUpdate: {
            name?: string;
            enabled?: boolean;
            spec?: components["schemas"]["ScheduleSpec"];
            action?: components["schemas"]["ScheduleAction"];
            delivery?: components["schemas"]["DeliveryTarget"][];
        };
        Usage: {
            prompt_tokens: number;
            completion_tokens: number;
            total_tokens: number;
            /** @default 0 */
            cost_usd: number;
        };
        Model: {
            id: string;
            /**
             * @description Open enum
             * @example omlx
             * @example ollama
             * @example remote
             */
            provider: string;
            /**
             * @description Open enum — routing tier (M-D)
             * @example local
             * @example remote
             * @example lora
             */
            tier: string;
            loaded: boolean;
        };
        ToolInfo: {
            name: string;
            /**
             * @description Open enum
             * @example builtin
             * @example mcp
             * @example module
             */
            source: string;
            description: string;
            risk_class?: components["schemas"]["RiskClass"];
            /**
             * @description DERIVED from risk_class (true for anything but `read`). Present for pre-H1 clients; new consumers should read risk_class, which carries strictly more information. Absent (pre-H1 daemon) means the class is unknown, which is treated as `external`, not as `read`.
             * @default false
             */
            requires_approval: boolean;
        };
        /**
         * @description A tool's intrinsic side-effect category (H1). Each class earns a different exemption path, which is the reason for the split: only `external` may ever be covered by a target-scoped standing grant; `exec` is asked every time. `read` covers network reads (an http GET changes nothing) — exfiltration is a taint concern, not a side effect. Omitted by a pre-H1 daemon, in which case treat it as `external`.
         * @example read
         * @example external
         * @enum {string}
         */
        RiskClass: "read" | "write_local" | "exec" | "external";
        RiskOverride: {
            /**
             * @description Glob over tool names; also the rule's identity.
             * @example mcp_fs_*
             */
            pattern: string;
            risk_class: components["schemas"]["RiskClass"];
            /**
             * @description Surface the user acted from. Audit metadata, NOT authorization.
             * @example desktop
             * @example cli
             * @example tui
             */
            source: string;
            /** Format: date-time */
            created_at: string;
        };
        ErrorBody: {
            /**
             * @description Open enum: invalid_request, unauthorized, not_found, conflict,
             *     approval_already_resolved, provider_unavailable,
             *     run_not_cancellable (reserved), internal
             */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        Error: {
            error: components["schemas"]["ErrorBody"];
        };
    };
    responses: {
        /** @description Malformed or invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No LLM provider reachable */
        ProviderUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        PathId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daemon is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    postChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Completed chat response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            503: components["responses"]["ProviderUnavailable"];
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        models: components["schemas"]["Model"][];
                    };
                };
            };
        };
    };
    getUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregate usage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usage"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessions: components["schemas"]["Session"][];
                    };
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                status?: components["schemas"]["RunStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runs: components["schemas"]["Run"][];
                    };
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Run accepted (status=queued) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested (or run already terminal) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listApprovals: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApprovalStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approval list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        approvals: components["schemas"]["Approval"][];
                    };
                };
            };
        };
    };
    decideApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Decision applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Approval already resolved or expired */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "approval_already_resolved",
                     *         "message": "Approval apr_01H… was already resolved (status=timed_out)"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listSchedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schedule list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        schedules: components["schemas"]["Schedule"][];
                    };
                };
            };
        };
    };
    createSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleCreate"];
            };
        };
        responses: {
            /** @description Created (next_run_at computed) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schedule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleUpdate"];
            };
        };
        responses: {
            /** @description Updated schedule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    runScheduleNow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run_id: string;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    shutdownDaemon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shutdown initiated */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                    };
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tool list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tools: components["schemas"]["ToolInfo"][];
                    };
                };
            };
        };
    };
    listToolOverrides: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Override list, most specific rule first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        overrides: components["schemas"]["RiskOverride"][];
                    };
                };
            };
        };
    };
    setToolOverride: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Glob over tool names (`*` any run, `?` one char). It is the rule's identity, so writing the same pattern twice replaces it. */
                pattern: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    risk_class: components["schemas"]["RiskClass"];
                    /**
                     * @description Surface the user acted from. Audit metadata, NOT authorization.
                     * @example desktop
                     * @example cli
                     * @example tui
                     */
                    source?: string;
                };
            };
        };
        responses: {
            /** @description The stored rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskOverride"];
                };
            };
            /** @description Empty pattern */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteToolOverride: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Glob over tool names (`*` any run, `?` one char). It is the rule's identity, so writing the same pattern twice replaces it. */
                pattern: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such rule */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
